name: 'Publish-truefipreview'
description: 'Upload files to server'
inputs:
  files:
    description: 'Build folder'
    required: true
  id:
    description: 'Commit id'
    required: true
outputs:
  url:
    description: 'Url to preview'
runs:
  using: 'node16'
  main: 'index.js'
