name: 'Publish-truefipreview'
description: 'Upload files to server'
inputs:
  files:
    description: 'Build folder'
    required: true
  access-token:
    description: 'Access token'
    required: true
  owner:
    description: 'Owner name'
    required: true
  repo:
    description: 'Repo name'
    required: true
  pull_number:
    description: 'PR number'
    required: true
  server-url:
    description: 'Url of preview server'
    default: test
    required: true
outputs:
  url:
    description: 'Url to preview'
runs:
  using: 'node16'
  main: 'src/index.js'
